name: Build Status

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - CONTRIBUTING.md
      - LICENSE
      - README.md
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Print System Information
      run: echo "Platform: $(uname -a)"

    - name: Install dependencies
      run: npm install --no-optional

    - name: Build
      run: npx hardhat compile

    # - name: Lint
    #   run: npx hardhat lint

    - name: Test
      run: npx hardhat coverage

    - name: Upload coverage
      uses: codecov/codecov-action@v3